import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('asdfgh'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Window Hanging - Pink Flower',
      slug: 'teal-pink',
      category: 'Window Hangings',
      image: '/images/teal_pink_win.jpg',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Window Hanging - Pink Berries',
      slug: 'green-pink',
      category: 'Window Hangings',
      image: '/images/green_pink_win.jpg',
      price: 80,
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Window Hanging - Skull',
      slug: 'brown-red',
      category: 'Window Hangings',
      image: '/images/brown_red_win.jpg',
      price: 90,
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'A popular shirt',
    },
    {
      name: 'Window Hanging - Green & White Flower',
      slug: 'brown-green',
      category: 'Window Hangings',
      image: '/images/brown_green_win.jpg',
      price: 90,
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Smart looking pants',
    },
    // {
    //   name: 'Window Hanging - Succulents',
    //   slug: 'purple-green',
    //   category: 'Window Hangings',
    //   image: '/images/purple_green_win.jpg',
    //   price: 95,
    //   rating: 3.5,
    //   numReviews: 7,
    //   countInStock: 20,
    //   description: 'A popular pants',
    // },
    {
      name: 'Window Hanging - Orange Berries',
      slug: 'green-orange',
      category: 'Window Hangings',
      image: '/images/green_orange_win.jpg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Window Hanging - Purple Flower',
      slug: 'brown-purple',
      category: 'Window Hangings',
      image: '/images/brown_purple_win.jpg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'Window Hanging - Purple Flower',
      slug: 'grey-purple',
      category: 'Window Hangings',
      image: '/images/gray_purple_win.jpg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'USB Cover - Pink Flower',
      slug: 'gray-pink',
      category: 'USB Covers',
      image: '/images/USB_gray_pink.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'USB Cover - Vines',
      slug: 'green',
      category: 'USB Covers',
      image: '/images/USB_green.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'USB Cover - Orange Berries',
      slug: 'orange-pink',
      category: 'USB Covers',
      image: '/images/USB_orange_pink.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'USB Cover - Navy',
      slug: 'navy-pink',
      category: 'USB Covers',
      image: '/images/USB_navy_pink.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'USB Cover - Red Flower',
      slug: 'red-brown',
      category: 'USB Covers',
      image: '/images/USB_brown_red.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'USB Cover - Red',
      slug: 'red-pink',
      category: 'USB Covers',
      image: '/images/USB_red_pink.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
    {
      name: 'USB Cover - Purple Flower',
      slug: 'green-purple',
      category: 'USB Covers',
      image: '/images/USB_green_purple.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'A popular pants',
    },
  ],
};

export default data;