import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('asdfgh'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Window Hanging - Pink Flower',
      slug: 'teal-pink',
      category: 'Window Hangings',
      image: '/images/teal_pink_win.jpg',
      price: 70,
      rating: 4.5,
      numReviews: 8,
      countInStock: 20,
      description: 'Consectetur ullamco ullamco eiusmod reprehenderit nostrud pariatur duis enim. Pariatur cillum non est elit excepteur aliquip voluptate culpa. Deserunt commodo quis ipsum culpa dolore excepteur consectetur sit. Non dolore culpa ipsum cupidatat minim ad anim velit. Laborum ut deserunt eiusmod elit. Sunt ea dolore adipisicing occaecat incididunt reprehenderit duis non occaecat ea. Magna consequat aliqua magna aliqua laboris exercitation non officia exercitation ex mollit.',
    },
    {
      name: 'Window Hanging - Pink Berries',
      slug: 'green-pink',
      category: 'Window Hangings',
      image: '/images/green_pink_win.jpg',
      price: 80,
      rating: 3.2,
      numReviews: 10,
      countInStock: 20,
      description: 'Sunt proident proident nulla eiusmod in. Eiusmod aliquip consequat sint occaecat eu nostrud anim nostrud ipsum qui. Consectetur tempor veniam nisi dolore culpa sunt laborum.',
    },
    {
      name: 'Window Hanging - Skull',
      slug: 'brown-red',
      category: 'Window Hangings',
      image: '/images/brown_red_win.jpg',
      price: 90,
      rating: 4.5,
      numReviews: 3,
      countInStock: 20,
      description: 'Velit eu tempor veniam quis non aliqua tempor. Ad ad esse ullamco enim proident est aliquip esse adipisicing sit duis ut laborum esse. Labore reprehenderit laboris aliquip amet mollit anim excepteur esse veniam adipisicing reprehenderit anim ullamco. Veniam ullamco tempor id elit veniam elit eu commodo. Sint esse culpa officia incididunt dolore. Exercitation fugiat laboris mollit esse nisi non eiusmod aliquip labore do commodo et Lorem. Non eiusmod velit ullamco amet mollit est quis pariatur non labore velit laborum esse.',
    },
    {
      name: 'Window Hanging - Green & White Flower',
      slug: 'brown-green',
      category: 'Window Hangings',
      image: '/images/brown_green_win.jpg',
      price: 90,
      rating: 2.9,
      numReviews: 13,
      countInStock: 20,
      description: 'Ipsum esse ex irure officia incididunt incididunt do magna officia velit. Ex id incididunt commodo reprehenderit nostrud nostrud elit. Ut est Lorem mollit dolore culpa nisi. Sint ad velit deserunt velit ullamco enim sunt nulla. Do occaecat mollit irure mollit velit fugiat ex aliqua veniam nisi amet. Aliqua consectetur ex ea adipisicing enim quis deserunt nulla elit esse anim sit. Nisi voluptate mollit eu officia enim esse eu.',
    },
    // {
    //   name: 'Window Hanging - Succulents',
    //   slug: 'purple-green',
    //   category: 'Window Hangings',
    //   image: '/images/purple_green_win.jpg',
    //   price: 95,
    //   rating: 3.5,
    //   numReviews: 7,
    //   countInStock: 20,
    //   description: 'A popular pants',
    // },
    {
      name: 'Window Hanging - Orange Berries',
      slug: 'green-orange',
      category: 'Window Hangings',
      image: '/images/green_orange_win.jpg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Sunt elit duis enim laboris magna velit tempor fugiat pariatur ea cillum occaecat minim ut. Officia enim laboris sit amet dolore Lorem mollit id ut. Nulla do deserunt eiusmod qui excepteur laborum cillum eu aute pariatur irure duis do sint. Ipsum fugiat voluptate qui dolore tempor non quis nulla labore mollit cupidatat. Laboris velit veniam sunt minim est consectetur ipsum.',
    },
    {
      name: 'Window Hanging - Purple Flower',
      slug: 'brown-purple',
      category: 'Window Hangings',
      image: '/images/brown_purple_win.jpg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Velit est commodo sint ullamco elit velit aliqua eiusmod laboris labore pariatur do occaecat dolor. Sit enim sit nulla non nulla aliqua eiusmod labore dolor. Nostrud labore reprehenderit enim Lorem dolore ipsum enim sint sint tempor. Velit tempor mollit duis amet aute culpa officia et occaecat cupidatat enim id.',
    },
    {
      name: 'Window Hanging - Purple Flower',
      slug: 'grey-purple',
      category: 'Window Hangings',
      image: '/images/gray_purple_win.jpg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Cupidatat est nisi sint labore eu cupidatat. Deserunt amet laborum exercitation consequat consectetur consectetur nostrud amet. Commodo ea deserunt tempor laborum magna fugiat id nisi enim nisi incididunt.',
    },
    {
      name: 'USB Cover - Pink Flower',
      slug: 'gray-pink',
      category: 'USB Covers',
      image: '/images/USB_gray_pink.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Reprehenderit veniam excepteur irure dolore est ea velit quis. Cupidatat aliqua ex anim deserunt tempor dolor incididunt id quis exercitation. Dolor laborum id do qui nostrud Lorem velit incididunt cillum amet ullamco esse. Labore laborum elit cupidatat est culpa. Eu nulla aliqua velit est sint excepteur sint. Sunt cillum qui eiusmod do et in sunt mollit. Velit nisi reprehenderit qui nulla qui ad ullamco ex irure irure voluptate nostrud.',
    },
    {
      name: 'USB Cover - Vines',
      slug: 'green',
      category: 'USB Covers',
      image: '/images/USB_green.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Nisi eu id tempor sunt minim ullamco consequat adipisicing qui. Et exercitation laborum dolore exercitation Lorem dolore enim esse nulla. Consequat anim excepteur sunt ipsum. Incididunt minim nostrud amet nulla ex nulla exercitation enim reprehenderit irure eu ea veniam enim. Eu ea dolore elit officia veniam qui laborum tempor officia. Cupidatat labore nisi tempor quis irure eiusmod. Duis cupidatat fugiat aute velit amet ex deserunt.',
    },
    {
      name: 'USB Cover - Orange Berries',
      slug: 'orange-pink',
      category: 'USB Covers',
      image: '/images/USB_orange_pink.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Adipisicing ad aute qui ea incididunt labore elit laborum. Do aute deserunt eu in excepteur do aliquip Lorem proident. Magna ad occaecat aute occaecat mollit id ipsum enim qui eiusmod do laborum ullamco ipsum. Ex sint consequat commodo labore nostrud eiusmod sint magna veniam. Commodo veniam cupidatat dolor esse culpa laborum consequat excepteur nisi eiusmod Lorem officia elit sint. Velit qui nulla id incididunt consequat elit laborum.',
    },
    {
      name: 'USB Cover - Navy',
      slug: 'navy-pink',
      category: 'USB Covers',
      image: '/images/USB_navy_pink.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Elit esse labore laboris ut quis mollit mollit laboris aliqua. Laboris deserunt aliqua culpa in anim amet nisi. Incididunt nisi ullamco minim nulla amet. Ex tempor incididunt irure pariatur aliqua exercitation. Minim proident quis commodo officia non minim ut magna consequat nisi Lorem. Dolor cillum cillum exercitation aliqua officia. Nisi non id quis sunt consectetur consectetur pariatur.',
    },
    {
      name: 'USB Cover - Red Flower',
      slug: 'red-brown',
      category: 'USB Covers',
      image: '/images/USB_brown_red.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Amet duis aliquip enim velit non voluptate. Est aliqua occaecat reprehenderit nulla. Dolor nulla veniam aliquip officia tempor aliquip adipisicing non ut velit velit. Sunt veniam duis id cupidatat labore voluptate quis incididunt laboris ullamco. Est quis proident consequat anim non deserunt laboris esse qui consectetur tempor et. Nisi excepteur deserunt incididunt tempor aute ut.',
    },
    {
      name: 'USB Cover - Red',
      slug: 'red-pink',
      category: 'USB Covers',
      image: '/images/USB_red_pink.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Eu ipsum do ad et. Consectetur occaecat amet quis est minim ea Lorem id eu dolor culpa exercitation. Officia anim id sint aliquip anim duis duis culpa fugiat ad est dolore. Mollit consectetur eu dolor velit non.',
    },
    {
      name: 'USB Cover - Purple Flower',
      slug: 'green-purple',
      category: 'USB Covers',
      image: '/images/USB_green_purple.jpeg',
      price: 75,
      rating: 2.4,
      numReviews: 14,
      countInStock: 20,
      description: 'Sunt fugiat veniam labore irure cupidatat voluptate ad laboris reprehenderit velit. Ex cupidatat ad magna esse et dolor excepteur. Nisi do occaecat tempor sint irure excepteur anim proident ut velit pariatur.',
    },
  ],
};

export default data;